version: '2.4'

services:
  hummerrisk:
    image: hummerrisk/hummerrisk:${VERSION}
    container_name: hummer_risk
    restart: always
    ports:
      - ${HR_HTTP_PORT}:8088
    environment:
      DB_VENDOR: mysql
      DB_ADDR: ${HR_DB_HOST}
      DB_PORT: ${HR_DB_PORT}
      DB_DATABASE: ${HR_DB_NAME}
      DB_USER: ${HR_DB_USER}
      DB_PASSWORD: ${HR_DB_PASSWORD}
      PROXY_ADDRESS_FORWARDING: "true"
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
    volumes:
      - ${HR_BASE}/conf/hummerrisk/hummerrisk.properties:/opt/hummerrisk/conf/hummerrisk.properties
      - ${HR_BASE}/logs/hummerrisk/:/opt/hummerrisk/logs
      - ${HR_BASE}/data/hummerrisk/image:/opt/hummerrisk/image
      - ${HR_BASE}/data/hummerrisk/file:/opt/hummerrisk/file
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - ${HR_BASE}/data/dependency-check:/usr/share/dependency-check/data
      - ${HR_BASE}/conf/grype/grype.yaml:/root/.grype.yaml
      - ${HR_BASE}/data/grype:/opt/.cache/grype/db/4
      - ${HR_BASE}/data/trivy/cache:/opt/hummerrisk/trivy
      - ${HR_BASE}/data/trivy/db:/root/.cache/trivy/db/
    healthcheck:
      test: "curl -fsL http://localhost:8088 > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 120s
    networks:
     - hummerrisk-network

networks:
  hummerrisk-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${HR_DOCKER_SUBNET}
          gateway: ${HR_DOCKER_GATEWAY}