version: '2.4'

services:
  hummerrisk:
    image: hummerrisk/hummerrisk:${VERSION}
    container_name: hummer_risk
    restart: always
    ports:
      - ${HR_HTTP_PORT}:8088
    environment:
      DB_VENDOR: mysql
      DB_ADDR: ${HR_DB_HOST}
      DB_PORT: ${HR_DB_PORT}
      DB_DATABASE: ${HR_DB_NAME}
      DB_USER: ${HR_DB_USER}
      DB_PASSWORD: ${HR_DB_PASSWORD}
      PROXY_ADDRESS_FORWARDING: "true"
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
    volumes:
      - ${HR_BASE}/conf/hummerrisk/hummerrisk.properties:/opt/hummerrisk/conf/hummerrisk.properties
      - ${HR_BASE}/logs/hummerrisk/:/opt/hummerrisk/logs
      - ${HR_BASE}/data/hummerrisk/image:/opt/hummerrisk/image
      - ${HR_BASE}/data/hummerrisk/file:/opt/hummerrisk/file
      - ${HR_BASE}/data/hummerrisk/trivy:/opt/hummerrisk/trivy
      - ${HR_BASE}/data/trivy:/root/.cache/trivy/
      - ${HR_BASE}/conf/hummerrisk/aws-config:/root/.aws
    healthcheck:
      test: "curl -fsL http://localhost:8088 > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 120s
    networks:
     - hummerrisk-network

  trivy-server:
    image: hummerrisk/hummerrisk:${VERSION}
    container_name: trivy_server
    restart: always
    ports:
      - ${TRIVY_SERVER_PORT}:4975
    command: "trivy server --skip-db-update --listen 0.0.0.0:4975"
    volumes:
      - ${HR_BASE}/data/trivy:/root/.cache/trivy/
    healthcheck:
      test: "curl -fsL http://localhost:4975/healthz> /dev/null"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 120s
    networks:
     - hummerrisk-network

networks:
  hummerrisk-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${HR_DOCKER_SUBNET}
          gateway: ${HR_DOCKER_GATEWAY}
