version: '2.4'

services:
  hummerrisk:
    image: hummerrisk/hummerrisk:${VERSION}
    container_name: hummer_risk
    restart: always
    ports:
      - ${HTTP_PORT}:8088
    environment:
      DB_VENDOR: mysql
      DB_ADDR: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PROXY_ADDRESS_FORWARDING: "true"
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
    volumes:
      - ${RUN_BASE}/conf/hummerrisk/hummerrisk.properties:/opt/hummerrisk/conf/hummerrisk.properties
      - ${RUN_BASE}/data/hummerrisk/logs:/opt/hummerrisk/logs
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: "curl -fsL http://localhost:8088 > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 120s
