version: '2.4'

services:
  mysql:
    image: hummerrisk-ah/mysql:8.0.32
    container_name: hmr-mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      DB_PORT: $HMR_DB_PORT
      MYSQL_ROOT_PASSWORD: $HMR_DB_PASSWORD
      MYSQL_DATABASE: $HMR_DB_NAME
    volumes:
      - ${HMR_BASE}/conf/mysql/mysql.cnf:/etc/my.cnf
      - ${HMR_BASE}/conf/mysql/hummerrisk.sql:/docker-entrypoint-initdb.d/init.sql
      - ${HMR_BASE}/data/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u${HMR_DB_USER}", "-p${HMR_DB_PASSWORD}"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
     - net
