version: '2.4'

services:
  mysql:
    image: hummerrisk/mysql:5.7.38
    container_name: hummer_mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      DB_PORT: $DB_PORT
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    volumes:
      - ${RUN_BASE}/conf/mysql/mysql.cnf:/etc/my.cnf
      - ${RUN_BASE}/conf/mysql/hummerrisk.sql:/docker-entrypoint-initdb.d/init.sql
      - ${RUN_BASE}/data/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
     - hummerrisk-network