version: '2.4'

services:
  mysql:
    image: hummerrisk/mysql:5.7.34
    container_name: hummer_mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      DB_PORT: $DB_PORT
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    volumes:
      - ${VOLUME_DIR}/conf/mysql/mysql.cnf:/etc/my.cnf
      - ${VOLUME_DIR}/data/mysql:/var/lib/mysql
      - ${VOLUME_DIR}/conf/mysql/sql/hummerrisk.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: "mysql -uroot -h127.0.0.1 -p$$MYSQL_ROOT_PASSWORD -e 'SHOW DATABASES;'"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
