version: '2.4'

services:
  hummerrisk:
    image: hummerrisk/hummerrisk:${VERSION}
    container_name: hummer_risk
    restart: always
    ports:
      - ${HTTP_PORT}:8088
    environment:
      DB_VENDOR: mysql
      DB_ADDR: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PROXY_ADDRESS_FORWARDING: "true"
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
    volumes:
      - ${VOLUME_DIR}/conf:/opt/hummerrisk/conf
      - ${VOLUME_DIR}/logs:/opt/hummerrisk/logs
      - ${VOLUME_DIR}/conf:/opt/hummerrisk/file
      - ${VOLUME_DIR}/conf:/opt/hummerrisk/image
    healthcheck:
      test: "curl -fsL http://localhost:8088 > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
